### ISSUE TITLE
express 5 router wildcard does not work as documented

### ISSUE THREAD

**Issue by david-gang** [expressjs/expressjs.com#1408]
Hi,

The following does not work as written in the documentation:
https://expressjs.com/en/5x/api.html

```
app.all('*', requireAuthentication, loadUser)

```

This is because you are at a newer version of path-to-regexp

https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x

so please update the documentation because this works

```
app.all('(.*)', requireAuthentication, loadUser)
```

I think that also the migration doc should reflect this change.

Thanks

**Comment by david-gang** [comment]
@dougwilson  I could open a PR with the documentation changes. English is not my mother tongue so i would prefer that a native english speaker will review the PR. What do you think ?

**Comment by IamLizu** [comment]
Hey @david-gang 👋 

Thank you for your contribution 🎉

You can start this, if you are still here, please respond and I think someone will assign this to you.

**Comment by david-gang** [comment]
Hi,

I am not longer using express actively.  

Sorry,

**Comment by IamLizu** [comment]
Hey @david-gang 👋 

Its fine. 

In that case, I willing to fix it. 

cc: @UlisesGascon

**Comment by IamLizu** [comment]
Quick question, I have noticed that express 5.0 is not using `path-to-regex`, [_not listed as dependency_.](https://github.com/expressjs/express/blob/5.0/package.json). Why is that?

Edit: It appears that `express` 5 is using `router` which is using `path-to-regexp` "3.2.0".

**Comment by IamLizu** [comment]
We already have PR for this which is ready to be landed, 

- https://github.com/expressjs/expressjs.com/pull/1369

**Comment by crandmck** [comment]
Fixed by #1369

**Comment by osakdv** [comment]
Still encountered issues using either `'*'` or `'(.*)'`   - in Express 5, these throw a missing parameter name error and fail to parse properly.

The route pattern i use that works fine is this: 
`/^\/(?!api).*/`

`app.all(/^\/(?!api).*/, requireAuthentication, loadUser)`

NOTE: This excludes all routes starting with **/api** - api related routes

**Comment by bjohansebas** [comment]
@osakdv https://expressjs.com/en/guide/migrating-5.html#path-syntax

**Comment by Josehower** [comment]
this also my be interesting to see https://www.linkedin.com/posts/furqanahmad03_expressjs-webdevelopment-deployment-activity-7326959821352525824-4hk_
